name: wideli
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  sqflite: ^2.3.0
  path: any
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  mobile_scanner: ^3.5.1
  image_picker: ^1.0.4
  firebase_core: ^2.32.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.15.1
  flutter_card_swiper: any

  flutter_svg: ^2.0.9

  # State Management (pilihan)
  provider: ^6.1.1

  # Network dan Image
  http: ^1.1.0
  cached_network_image: ^3.3.0

  # UI Components tambahan
  flutter_staggered_grid_view: ^0.7.0
  my: ^1.1.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/kantin1.jpg
    - assets/images/kantin2.jpg
    - assets/images/kantin3.jpg
    - assets/images/kantin4.jpeg
    - assets/images/lutfi.png
    - assets/images/user.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  image_path: "assets/icon/wideli.png"